#include "usblib/usbhid.h"
#include <stdint.h>

#define WINDOWS_KEY 0x65
#define PAUSE 0xE8
#define DELETE 0x4C
#define HOME 0x4A
#define END 0x4D
#define INSERT 0x49
#define MUTE 0xEF
#define PREV 0xEA
#define NEXT 0xEB
#define CALC 0xFB
#define VOL_UP 0xED
#define VOL_DN 0xEE
void Switch_Init(void);
void Switch_Stop(void);
void Switch_Start(void);

uint8_t KeyboardMatrix[2][5][14] = {
  {
    {HID_KEYB_USAGE_BQUOTE,  HID_KEYB_USAGE_1, HID_KEYB_USAGE_2, HID_KEYB_USAGE_3, HID_KEYB_USAGE_4, HID_KEYB_USAGE_5, HID_KEYB_USAGE_6, HID_KEYB_USAGE_7, HID_KEYB_USAGE_8, HID_KEYB_USAGE_9, HID_KEYB_USAGE_0, HID_KEYB_USAGE_MINUS, HID_KEYB_USAGE_EQUAL, HID_KEYB_USAGE_BACKSPACE},
    {HID_KEYB_USAGE_TAB, HID_KEYB_USAGE_Q, HID_KEYB_USAGE_W, HID_KEYB_USAGE_E, HID_KEYB_USAGE_R, HID_KEYB_USAGE_T, HID_KEYB_USAGE_Y, HID_KEYB_USAGE_U, HID_KEYB_USAGE_I, HID_KEYB_USAGE_O, HID_KEYB_USAGE_P, HID_KEYB_USAGE_LBRACKET, HID_KEYB_USAGE_RBRACKET, HID_KEYB_USAGE_BSLASH},
    {HID_KEYB_CAPS_LOCK, HID_KEYB_USAGE_A, HID_KEYB_USAGE_S, HID_KEYB_USAGE_D, HID_KEYB_USAGE_F, HID_KEYB_USAGE_G, HID_KEYB_USAGE_H, HID_KEYB_USAGE_J, HID_KEYB_USAGE_K, HID_KEYB_USAGE_L, HID_KEYB_USAGE_SEMICOLON, HID_KEYB_USAGE_FQUOTE, 0, HID_KEYB_USAGE_ENTER},
    {HID_KEYB_LEFT_SHIFT, 0, HID_KEYB_USAGE_Z, HID_KEYB_USAGE_X, HID_KEYB_USAGE_C, HID_KEYB_USAGE_V, HID_KEYB_USAGE_B, HID_KEYB_USAGE_N, HID_KEYB_USAGE_M, HID_KEYB_USAGE_COMMA, HID_KEYB_USAGE_PERIOD, HID_KEYB_USAGE_FSLASH, HID_KEYB_RIGHT_SHIFT, 0},
    {HID_KEYB_LEFT_CTRL, 0x65, HID_KEYB_LEFT_ALT, 0, 0, HID_KEYB_USAGE_SPACE, 0, 0, 0, HID_KEYB_USAGE_LEFT_ARROW, HID_KEYB_USAGE_DOWN_ARROW, HID_KEYB_USAGE_UP_ARROW, HID_KEYB_USAGE_RIGHT_ARROW, 0}
  },
  {
    {HID_KEYB_USAGE_ESCAPE, HID_KEYB_USAGE_F1, HID_KEYB_USAGE_F2, HID_KEYB_USAGE_F3, HID_KEYB_USAGE_F4, HID_KEYB_USAGE_F5, HID_KEYB_USAGE_F6, HID_KEYB_USAGE_F7, HID_KEYB_USAGE_F8, HID_KEYB_USAGE_F9, HID_KEYB_USAGE_F10, HID_KEYB_USAGE_F11, HID_KEYB_USAGE_F12, DELETE},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, PAUSE, HOME, END, INSERT},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, CALC, 0, 0, 0, MUTE, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, PREV, VOL_DN, VOL_UP, NEXT}
  }
  } ;